### ISSUE TITLE
This is the BEST on-screen crosshair app !!! (Lighter Crosshairs)

### ISSUE THREAD

**Issue by z-f-s** [lacymorrow/crossover#104]
There are so many crosshair and their colors, but ... why is there no choice of white? For example, at the usual dot - Dot Outlined and Dot Simple. Really need white, please.

**Comment by lacymorrow** [comment]
Why no white? Good question, mainly because I didn't make any of the crosshairs and I use a red or green dot :)

Ask and you shall receive though, I have a caveman's understanding of editing photos, so I've made some off-white versions of the colored crosshairs and named them `Light`.

See the latest release: https://github.com/lacymorrow/crossover/releases/latest
