### ISSUE TITLE
Stolen work from you!

### ISSUE THREAD

**Issue by G-Rowell** [lacymorrow/crossover#105]
Hi,

your repo here,

Has been stolen & re-uploaded by the GitHub user: https://github.com/5R33CH4

Here is their repo in which they've stolen your work, and attributed it to themselves: https://github.com/5R33CH4/OneShot

They also have a GitHub org, where they likely also have some stolen work: https://github.com/tesseract-org.

Checkout their all their personal repos...

I'm sorry to bring you this bad news, this user has stolen >50 repos so you should consider reporting them to GitHub.

Galen

**Comment by 5R33CH4** [comment]
> Hi,
> 
> your repo here,
> 
> Has been stolen & re-uploaded by the GitHub user: https://github.com/5R33CH4
> 
> Here is their repo in which they've stolen your work, and attributed it to themselves: https://github.com/5R33CH4/OneShot
> 
> They also have a GitHub org, where they likely also have some stolen work: https://github.com/tesseract-org.
> 
> Checkout their all their personal repos...
> 
> I'm sorry to bring you this bad news, this user has stolen >50 repos so you should consider reporting them to GitHub.
> 
> Galen

Well kido, first learn coding before accusing . see the difference between the codes of one shot and crossover. Oneshot is based on an older version of crossover with much more crosshairs than what they offered at that time.

**Comment by G-Rowell** [comment]
Downloading a repo.....

removing all evidence of the original author, and re-branding it as your own....

with absolutely no attribution to the original project....


well that's just theft.

---

First learn coding?
I'm a senior university student & staff, I think I know coding?

**Comment by lacymorrow** [comment]
@G-Rowell Thanks for the heads-up.

@5R33CH4 I'll state this again in your repo, but it's in poor taste to modify someone's source code, and redistribute it without any sort of attribution or note of the original creator. 

You're essentially using my code, logo, image assets, and documentation while explicitly removing all credits to original authors of the images as well as myself. It's a little shady, to say the least.

Best practice in this situation would be:
- Fork my repo so that users may trace the history of the source and find the original project (showing the ancestry and making it more easy to share changes).
- Retain all credits for assets within the project
- Add an attribution in the `README` to the original author
- Create a pull request back to the original project with your improvements to prevent fracturing of projects.

It's not illegal but it is arguably unethical to rename the project and begin to redistribute it without any breaking changes or improvements, however since you have done this you also should reach out to crosshair creators for permission to use their art for **your** new project (as I did).

What you did that **is** illegal however is removing my name from the copyright. This is copyright infringement and I am requesting that you:
- Fork my repository
- Reinstate the original `README` in it's full form, including all attributions and credits
- Reinstate the original copyright, as required by the MIT license.
- Stop harassing users on my repos. You had the chance to explain yourself and instead chose to insult others. Grow up and act like a professional.

**Comment by G-Rowell** [comment]
@lacymorrow 

Well said, couldn't have written a better response myself

my apologies again for bringing this headache to you.

---

Sadly I don't think this user has learnt, they're trying to hide their theft now that I've pointed it out: 

https://github.com/elzabrowser/elza/issues/8
> The user tried to remove more evidence by deleting a file that has your info in it: https://web.archive.org/web/20210928070301/https://github.com/tesseract-org/Nex/commit/a6033ebd9bee63c55134188018de4374e75bf954
>
> The file being deleted in the same commit: https://web.archive.org/web/20210928070631/https://github.com/tesseract-org/Nex/blob/50eff0fef68d8b8d9215f579e95a6baf11ab00d0/public/manifest.json

---

I have a lot of free time currently, hence my investigation, do you have any suggestions for me regarding this problem?

**Comment by SegoItCh** [comment]
> 
> 
> @G-Rowell Thanks for the heads-up.
> 
> @5R33CH4 I'll state this again in your repo, but it's in poor taste to modify someone's source code, and redistribute it without any sort of attribution or note of the original creator.
> 
> You're essentially using my code, logo, image assets, and documentation while explicitly removing all credits to original authors of the images as well as myself. It's a little shady, to say the least.
> 
> Best practice in this situation would be:
> 
>     * Fork my repo so that users may trace the history of the source and find the original project (showing the ancestry and making it more easy to share changes).
> 
>     * Retain all credits for assets within the project
> 
>     * Add an attribution in the `README` to the original author
> 
>     * Create a pull request back to the original project with your improvements to prevent fracturing of projects.
> 
> 
> It's not illegal but it is arguably unethical to rename the project and begin to redistribute it without any breaking changes or improvements, however since you have done this you also should reach out to crosshair creators for permission to use their art for **your** new project (as I did).
> 
> What you did that **is** illegal however is removing my name from the copyright. This is copyright infringement and I am requesting that you:
> 
>     * Fork my repository
> 
>     * Reinstate the original `README` in it's full form, including all attributions and credits
> 
>     * Reinstate the original copyright, as required by the MIT license.
> 
>     * Stop harassing users on my repos. You had the chance to explain yourself and instead chose to insult others. Grow up and act like a professional.

Yo, will you fix/close other issues here?

**Comment by lacymorrow** [comment]
@SegoItChI'm actively working on improving CrossOver, is there a specific feature or issue you would like to see worked on?

**Comment by SegoItCh** [comment]
@lacymorrow I mean close fixed issues and which not issues at all, I just love when everything is clean and sorted

**Comment by lacymorrow** [comment]
Yep, I'll clean up the issues a bit more. Cheers!
