### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by lacymorrow** [lacymorrow/crossover#147]
Add Typing and VSCode hints

**Comment by Eccomi21** [comment]
Since this is a good first issue, but i don't understand the issue, can you provide some more details what exactly you need? Hinting in VSCode as in snippets or intellisense/code completion style?

I'd like to help but don't know how, don't mind learning though if it is something i can work on in the background

**Comment by lacymorrow** [comment]
New release is written in TS
