### ISSUE TITLE
Feature Request: Add crossover to AUR

### ISSUE THREAD

**Issue by Jofre-Problem** [lacymorrow/crossover#192]
I think it will be really great idea to add this to the aur repository. Mostly because when installing the .pacman file, and when doing a system update, the update **conflicts** with CodeWeavers Crossover, causing a system error.

**Comment by begin-theadventure** [comment]
I used this application some time ago and wondered why it isn't on the Arch User Repository.
Could it be because of the name? I don't know, but I think the project name should be changed.

Anyway, now that I have some packages there myself, I did a PKGBUILD and edited a few things to avoid conflicts with the original CrossOver:
https://aur.archlinux.org/packages/crossover-overlay-bin

**Comment by lacymorrow** [comment]
How can I automate this submission process?
cc @begin-theadventure

**Comment by begin-theadventure** [comment]
It was added by me and I'm currently the maintainer, however, if you'd like to manage it, then I could orphan the package and let you adopt it.

**Comment by lacymorrow** [comment]
What files are you posting? I'm not familiar with AUR

**Comment by begin-theadventure** [comment]
AUR mainly consists of PKGBUILDs, which are basically shell script instructions, whether for building or for binary files.
In this case, it downloads a specified version of the .rpm package from GitHub and then repackages it accordingly.

**Comment by lacymorrow** [comment]
If you have a shell script handy or want to PR this into my CI, you would be the man. I don't have a lot of free time.

**Comment by lacymorrow** [comment]
Tracking: https://github.com/lacymorrow/crossover/issues/192#issuecomment-1577575952
