### ISSUE TITLE
Not working on Vulkan api borderless mode

### ISSUE THREAD

**Issue by dhabak777** [lacymorrow/crossover#26]
I play Rainbow Six Siege through the vulkan API exe. The overlay doesn't show up even in borderless mode. Any fix for this?

**Comment by lacymorrow** [comment]
I'll try to find a demo to test, thanks for flagging @dhabak777

**Comment by lacymorrow** [comment]
Related to #1

**Comment by dhabak777** [comment]
So, this one will take some time?

**Comment by lacymorrow** [comment]
Yes, unfortunately this one may take lots of time or may be un-fixable with the current technologies being used by CrossOver. I'm looking into the Vulkan API so it really depends on how the game developers have set things up.

**Comment by lacymorrow** [comment]
It seems that this issue is prevalent for Electron apps attempting to overlay on Vulkan apps and affects the Discord overlay as well. The app identifier is `com.lacymorrow.crossover` if that helps in your testing.

I actually purchased a copy of R6 to test and am going to try disabling hardware acceleration so we'll see if anything works.
