### ISSUE TITLE
Centered xhair?

### ISSUE THREAD

**Issue by arielsasson** [lacymorrow/crossover#30]
May be it's too subtle, but it seems crosshairs are not actually well centered in relation to the dot or cross. Which one should we be using?

**Comment by arielsasson** [comment]
UPDATE: I was curious and did a print screen and zoomed in with paint, and noticed the + crosshair (the basic one) is only one pixel thick. In a screen with even resolution dimensions, such as 1920*1080 you should use even amounts of pixels in the thickness of the lines, otherwise it will not be perfectly centered (this is due pixel 0 is undefined in the screen). I guess you could use 2 pixels for even dimensions. Also, I have been able to perfectly center the basic dot -I do this in Rust and it's very clear because the game itsef provides a barely bigger centered dot in a few situations (I just guess it's dimensions are even when size setting is at 100%). Then, when I switch to the basic + crosshair, the center dot happens to be in the pixel (960,540) so I guess the fix for this would be adding two more lines so that de center dot are the pixels (960,540) , (961,540) , (960,541) , (961,541). Generalizing to other cases would mean adding another line to the right of the vertical line, and another line below the horizontal one. Also, a "no center dot" option would be lovely 👍 . Thanks and hope this helps in any way.

**Comment by lacymorrow** [comment]
Sorry for the month-late reply, I appreciate the research you've done.

It's true because of the nature of pixels in a display, there is no real center pixel, only a pair. When faced with the options of having a 2px-wide crosshair or a 1px-wide crosshair that is only centered "sometimes" (when the size of the sight allows it), I chose the latter because I wanted the thinnest possible crosshair. It could have been the wrong choice.

Due to the way Chrome renders DOM and canvas elements, sub-pixel rendering isn't possible BUT I think it should be possible using images (rather than drawing the dot/crosshair myself), so hopefully you can expect a PR in the next week or so.

There IS an option to turn off the crosshair/center dot, the "off" button next to them.
![image](https://user-images.githubusercontent.com/1311301/92411987-f4f0c280-f0fe-11ea-900e-f98c3d2d373e.png)
