### ISSUE TITLE
Change color of crosshair images (Aside from the dot or cross option)

### ISSUE THREAD

**Issue by seanjobennett** [lacymorrow/crossover#33]
Sorry if this shouldn't go into the "issues" section, but was curious if there could be a way to change the colors of the other crosshairs to something other than just the black/gray that they are normally. Or, if it can't be a feature, where are the crosshairs stored so I could change them manually myself? Again, sorry if this is the wrong place and thanks for reading regardless!

**Comment by lacymorrow** [comment]
I will look into this, due to some images being PNG it won't be possible to change the colors of all the images programmatically. You can however use your own image by dragging a file onto the Crosshair window.

If you would like to edit the crosshairs available in CrossOver, they're stored in this directory: https://github.com/lacymorrow/crossover/tree/master/src/static/crosshairs

Hope this helps!

**Comment by lacymorrow** [comment]
If someone can provide a set of crosshairs in SVG format, it would be possible to allow color customization.
Until that time, this is not possible since the images are PNG.

**Comment by GirkovArpa** [comment]
@lacymorrow [Here's](https://codepen.io/sosuke/pen/Pjoqqp) a way to colorize a black PNG using JS and CSS.

**Comment by GirkovArpa** [comment]
Here's another way with pure CSS, no JS:
```html
div {
  width: 100px;
  height: 100px;
  background: red;
  -webkit-mask-image: url(crosshair.png);
  -webkit-mask-repeat: no-repeat;
  -webkit-mask-size: 100px 100px;
}
```
It uses the crosshair image as a cookie-cutter over a red square so that the result is just a red crosshair.

I would have liked to demonstrate this in a fork but I can't get any of my changes to apply, even though my calls to `console.log` do work.
