### ISSUE TITLE
"Center the crosshair window" shortcut doesn't work well

### ISSUE THREAD

**Issue by boyess** [lacymorrow/crossover#53]
The "ctrl + alt + shift + c" shortcut doesn't work correctly crosshair is not in the middle.

**Comment by lacymorrow** [comment]
@boyess Can you do me a favor and tell me your Operating System and if the crosshair is too low, too high?

Would also be good to know your monitor resolution if possible.

Basically, this issue has been created before (#23) and games don't necessarily use the same center point, more info here: https://github.com/lacymorrow/crossover/issues/23#issuecomment-634811779

I'm willing to adjust the vertical center point slightly if it turns out that it is centering "above" true center for everyone, it's possible that windows isn't including the taskbar height in the window size (the way mac doesn't include the dock: https://github.com/sindresorhus/electron-util/issues/41).

**Comment by boyess** [comment]
i am using windows and the crosshair is higher then in game crosshairs. I am using two monitors my main monitor(the one i am playing games) is 1360x768 and the second monitor is 1600x900

**Comment by boyess** [comment]
> @boyess Can you do me a favor and tell me your Operating System and if the crosshair is too low, too high?
> 
> Would also be good to know your monitor resolution if possible.
> 
> Basically, this issue has been created before (#23) and games don't necessarily use the same center point, more info here: [#23 (comment)](https://github.com/lacymorrow/crossover/issues/23#issuecomment-634811779)
> 
> I'm willing to adjust the vertical center point slightly if it turns out that it is centering "above" true center for everyone, it's possible that windows isn't including the taskbar height in the window size (the way mac doesn't include the dock: [sindresorhus/electron-util#41](https://github.com/sindresorhus/electron-util/issues/41)).

i am using windows and the crosshair is higher then in game crosshairs. I am using two monitors my main monitor(the one i am playing games) is 1360x768 and the second monitor is 1600x900

**Comment by lacymorrow** [comment]
I fixed this upstream, will trickle down shortly: https://github.com/sindresorhus/electron-util/pull/44

**Comment by lacymorrow** [comment]
Fixed: https://github.com/lacymorrow/crossover/releases/tag/latest
