### ISSUE TITLE
Full Screen Applications cant open the Crosshair. (MacOs)

### ISSUE THREAD

**Issue by darealblack** [lacymorrow/crossover#56]
So when I full screen an app on Mac it just doesn't open the crosshair, but when I go back with no fullscreen it works. Please fix this since this is quite annoying to play on Non-Fullscreen. (I Tried adding the crosshair to the app but it failed)

Thank you!
dareal_black

**Comment by lacymorrow** [comment]
Hey @darealblack, unfortunately the way this app was created doesn't allow it to overlay most fullscreen games, as they bypass the windowing system.

At this point in time my only suggestion is to play in "windowed fullscreen" or "borderless" mode.

Can you tell me what game you're playing so that I can add it to the list? If I can I'll test it myself as well, but there's no guarantee I can make it work.
https://github.com/lacymorrow/crossover/issues/47

**Comment by darealblack** [comment]
Oh thanks, Im sorry to hear that. I will continue to play in Windowed full screen. I tried playing in Roblox but it failed in Fullscreen but worked with No fullscreen. I hope that helps

Thank you!
dareal_black

**Comment by GirkovArpa** [comment]
@lacymorrow I justed tested it on Roblox on Windows 10 x64 and it works in both fullscreen and non-fullscreen mode.

**Comment by slayrr** [comment]
> @lacymorrow I justed tested it on Roblox on Windows 10 x64 and it works in both fullscreen and non-fullscreen mode.

he said on Mac(os) not windows

**Comment by darealblack** [comment]
Bro, it has been more than 2 years, what are you doing here
