### ISSUE TITLE
Fullscreen games support

### ISSUE THREAD

**Issue by Chit132** [lacymorrow/crossover#62]
Hello! Sorry if this isn't the right place for this as this is my first time using GitHub and I couldn't find another way to contact you :( I came across this app when I was building an overlay app for games myself and no matter how hard I tried, I couldn't get it to appear over fullscreen games. I tried everything like alwaysOnTop, show, maximize, kiosk mode, etc. and I just couldn't get it to work D: I'm currently running Electron v12.0.1 on Windows 10. Any help would be appreciated. Sorry and thanks!

**Comment by lacymorrow** [comment]
Unfortunately there is currently no way to put an electron window above a full screen window. It's a problem for this app and many others, you would need to write a native extension in order to achieve what you want I think.

The way I do it in the app is here: https://github.com/lacymorrow/crossover/blob/f178a9e66b18d7e2e5be211736fbe3bc8e240c86/src/main.js#L449

It doesn't work for most fullscreen windows

**Comment by Chit132** [comment]
Aww I'm glad that at least a professional got my doubts cleared. Thanks so much for the quick and thorough response! I will let you know if I find a solution to this issue! Have a great one ❤️

**Comment by lacymorrow** [comment]
Cheers! I would be thrilled if you found a way to do it

**Comment by foolofdestiny** [comment]
https://github.com/lacymorrow/crossover/issues/246
https://github.com/lacymorrow/crossover/issues/62#issuecomment-803489602  

epic  games  has  unleashed  the  unreal  engine  and  the  fortnite  code  to  the  public...
  it  may  be  possible  for  someone  who  knows  C++ to  adapt  this  to   it...

**Comment by lacymorrow** [comment]
The problem is that leaves Linux (and maybe Mac) users in the dust, plus it will require a custom NativeExtension with electron. That plus I haven't worked with C in a decade....
