### ISSUE TITLE
Not really an issue more like a suggestion :) 

### ISSUE THREAD

**Issue by adeldueast** [lacymorrow/crossover#82]
Didn't know where else to post this, but being able to enter custom key binds would be nice. Also when playing a game like rust, it would be nice to have an option to disable the crosshair **while** holding R.Mouse. Great project !

*EDIT: previous posts have been made already  about this sry

**Comment by lacymorrow** [comment]
Yep! I'm actively working on this.

Long story long, I need to add a ton of settings in order to do custom keybinds, and the current settings window is already cluttered so I want to incorporate https://github.com/tkambler/electron-preferences, but there are a few bugs with that project I need to fix before I'll feel comfortable using it.

We're close.

**Comment by lacymorrow** [comment]
Duplicate: https://github.com/lacymorrow/crossover/issues/20
